language: go
go:
- 1.x
cache:
  pip: true
  directories:
  - "$HOME/.nvm"
  - "$HOME/.local"
before_cache:
- rm -f $HOME/.npm/anonymous-cli-metrics.json
sudo: false
before_script:
- nvm install --lts node
- pip install --user pylint
script:
- make all
- "./.travis.gofmt.sh"
- make test
- test/martian_test.py test/split_test/split_test.json
- test/martian_test.py test/split_test_go/split_test.json
- test/martian_test.py test/split_test_go/disable_test.json
- test/martian_test.py test/files_test/files_test.json
- test/martian_test.py test/fork_test/fork_test.json
- test/martian_test.py test/fork_test/fail1_test.json
- test/martian_test.py test/fork_test/retry_test.json
- test/martian_test.py test/fork_test/autoretry_pass.json
- test/martian_test.py test/fork_test/autoretry_fail.json
- pylint adapters/python/martian_shell.py
- pylint adapters/python/martian.py
- pylint test/martian_test.py
- make tarball
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: dBZPhakddKqoQhvJseeIHpbWyyrmZjdZ1oOsa+dR8v+yyIw1Lf9tVk4+3cearrbelxYf65ZqkQXQPWw2uZYvCQbNzMtU9hhzOwBi8/Wb8gWXlcNDjQso8iLP3Z77DeuyYg4CA7EiSbvIIFaFcUtucTAu5b0Wa0uPj7/PX37CT/6oGM9h4jdocSeI65XmB0YuraSNDAHaurWcwLZZG9PNeENTgbjvS218SUkg2HFFTeApLZCaNyxWYxEfsUcu5VXKCpSpsLm82u7XGuNVDhavMjxvH6SG1PgIdPf31N0ok5UocUVl0z4lrlT2/YEwLbI5XyLxFvqcdDN1MKvQREirPCOMMSdJivDTv87gLZGHev/C6+rEJaSXhqF158KN7VWSf9YCjNCiWgi5/E5RDdVDzmlGsLCWn+M1owWFbKAkdM0xCntcfN8Yx3jFCd2NxhKFsQOlpYZMCKmD0PWDqCUFIizkpli2jXeRJvm5NNu5iyjIJ5xJCfH56vBJMksQK9cdE4jqjz1ZuXo7AQrM8NHPOeAlp+GkfHkBdfja5kFvoP9mYANzViXinvYqxK/qnoo+Jd8XzVE+R/D0t6V9bHuoRDDc/nbvXJPxqSxhnPNUvzJpTkT5UYE3XC3Y5HicHBq09ulbMItKHWAu6J0nyefLNvnLmptTa0WqjSefPJv9kIo=
  file_glob: true
  file: martian-$TRAVIS_TAG-*.tar.gz
  on:
    repo: martian-lang/martian
    tags: true
