[package]
name = "martian"
version = "0.1.0"
authors = ["Patrick Marks <patrick@10xgenomics.com>"]

[dependencies]
libc = "*"
log = "*"
fern = "0.3.5"
chrono = ">=0.3.0"
rustc-serialize = "*"
backtrace = "*"
