[package]
name = "martian"
version = "0.1.0"
authors = ["Patrick Marks <patrick@10xgenomics.com>"]

[dependencies]
libc = "*"
log = "*"
fern = "*"
chrono = "0.2.25"
rustc-serialize = "*"
backtrace = "*"
