[package]
name = "martian"
version = "0.1.0"
authors = ["Patrick Marks <patrick@10xgenomics.com>"]

[dependencies]
libc = "*"
log = "*"
fern = "*"
chrono = "*"
serde = "^1.0.8"
serde_json = "*"
backtrace = "*"
failure = "*"
failure_derive = "*"
